### ISSUE TITLE
Preference: Unsure why using a different namespace?

### ISSUE THREAD

**Issue by ldunham1** [mikemalinowski/qute#2]
https://github.com/mikemalinowski/qute/blob/3c5e1c34eba7153ba564910963f5c48c7abd1b4c/qute/__init__.py#L74

Unsure why the package imports using a different namesapce?
If related to backwards compatibility, it might be clearer/cleaner to use aliases later on?
I can imagine a wide usage of both names depending on where its being imported from, which might cause unnecessary confusion.

**Comment by mikemalinowski** [comment]
The different namespace is to retain backward compatibility between qute version 2 and qute version 2. 
Everything from line 59 down is there to hold backward compat for import paths - meaning someone using qute version 2 can upgrade to version 3 without having to alter their code. 

These will get a deprecation warning in a minor release soon to come.

**Comment by ldunham1** [comment]
Understandable - although I dont understand why the method isnt imported under its own name and then an alias used for the old name?
Unless you expect devs to have used it from direct from the styling module?

**Comment by mikemalinowski** [comment]
the expected way to use it in v3 is...

qute.utilities.styling.apply(..)

but in v2 it was:
qute.applyStyle

so in order to retain backward compat, we import the apply function but name it to the old method name. 

With v3, we're trying to avoid functions being placed directly in the qute namespace, instead they should go into either utilties or extensions and be in a subcategory from there.

**Comment by mikemalinowski** [comment]
I plan to wrap all those backward compat imports with deprecation warnings, then in v4 they will be permanently removed
